var excuses = [
	"I woke up feeling janky. Gonna try to sleep it off.",
	"I'm feeling a bit janky.",
	"the ground is kind of wet.",
	"I got a flat on Valencia.",
	"I got a flat on Market.",
	"I think it's supposed to rain.",
	"I'm too out of shape.",
	"it's going to be really windy.",
	"I need to swap my tires.",
	"my axle bolt rusted to the fork.",
	"I don't have a bike that can go offroad.",
	"my pump is broken and I'm all out of CO2.",
	"I'm swamped at work this week.",
	"I'm going for a run instead.",
	"I can't ride until next week :(",
	"I'm in Texas.",
	"it really depends how early.",
	"I've got the janky leg.",
	"I'm gonna be driving the truck.",
	"I left my bike at work.",
	"I left my riding shoes at work.",
	"I'll be swimming.",
	"I have a race this weekend.",
	"I'm going to sleep in then crush an omelette.",
	"drunk and still awake at 9 PK.",
	"yoga for me.",
	"some jackass stole my saddle.",
	"I'm at a metal show.",
	"I'm having a rough sleep and coughing.",
	"I'm drunk and still awake at 2. So I'm out lol",
	"trying to decide if I want to ride or surf.",
	"nature is too metal.",
	"didn't listen to my alarm today :-\\ ",
	"drunk and riding my bike at 1 am!! I also had an edible.",
	"left my bike at BART.",
	"I'm actually still working. Ugh. Gonna sleep in tomorrow.",
	"gotta drop off the dog.",
	"going to bike party tomorrow night instead.",
	"I've been trying to get my snooze score up for the last two weeks. My body was complaining.",
	"gonna be too long for me this week, may do something shorter.",
	"I can't find my gloves.",
	"I can't find my socks.",
	"it's supposed to be kind of cold.",
	"it's supposed to be kind of wet.",
	"my bikes making noises.",
	"I'm out of shape.",
	"I'm gonna be too slow.",
	"I had too many Wes burgers. ",
	"I think I'm getting sick. ",
	"I drank too much beer. ",
	"gotta pick up the dog.",
	"my friends are getting married.",
	"I have an early meeting.",
	"having some tire issues.",
	"I'm actually just gonna take it easy. My legs are beat from yesterday.",
	"dang that's early.",
	"I started having a sore throat yesterday and it has only been getting worse. I now have a cough and feel a bit feverish.",
	"I'm going to use this as an opportunity to sleep in.",
	"I need to bail tomorrow unfortunately, sore throat.",
	"I'm feeling under the weather, down to ride on Friday though.",
	"it's going to be too dark.",
	"I left my helmet at work.",
	"depends how late I'm up tonight. I'll keep you posted.",
	"bailing tomorrow. Getting to bed too late, sorry.",
	"I'm likely opting for a lunch ride or yoga tomorrow.",
	"I'm only half committed to riding at 6... I'll check in later.",
	"I have a friend in town.",
	"I won't be riding tomorrow, but let me know if you guys grab coffee and maybe I will meet up!",
	"I'm out for tomorrow. Walking home from a date right now. Had quite a few drinks lol",
	"depends on timing.",
	"I was actually getting the beginnings of a cold as of yesterday.",
	"Derp. I forgot that my sister and I have plans tomorrow morning! Gonna watch the sunrise from the Castro.",
	"Haha I don't think I'm leaving my house til around 8:30",
	"I'm going to bail all together. 6 sounds horrible and it was my idea.",
	"sometimes sacrifice at the sun god's alter is a solitary act.",
	"can't ride tomorrow, I fell through a worm hole.",
	"no rain riding for me! Be safe.",
	"I'm such a bad coyote guys. I'll get a bike pump and be better next year :)",
	"I believe it's supposed to rain...a lot",
	"I'm sorry but I'm not gonna make it guys. Enjoy!!",
	"I fly out tomorrow night.",
	"sorry dudes I will not be able to join tomorrow but will be in the city with my bike/surfboard this weekend if anyone's up for a little somethin somethin",
	"I'm drunk and still committed.... Nevermind.",
	"I'm still cold from the Dudesgiving ride.",
	"I'm still out of town but I'm down this week!",
	"I'm going to see Star Wars then IKEA.",
	"my bike is in the shop until Wednesday.",
	"some of us are riding out in the Sierras the following weekend and don't want to be wiped out",
	"it's yoga day for me.",
	"I'm out...Been fighting a cold.",
	"I’m out. I’ve had a really busy week and have an earlier meeting tomorrow. Enjoy!",
	"actually…I’m sort of enjoying this wine, I think I’m gonna bail on my own ride call",
	"sorry folks, woke up and my elbow has stiffened up from a fall",
	"if we wake up and it's pouring rain then sleeeeep.",
	"I keep coughing and can't shake it.",
	"I've been home sick the past two days so I'm going to rest up tomorrow.",
	"I just realized I've been up for 27 hours straight now... hooray for traveling half way around the world.",
	"it's coming down pretty good out there man. Let's postpone for another day.",
	"I don't think I can muster it."
];

function excuseGen() {
	var excuse = excuses[Math.floor(Math.random() * excuses.length)];
	$("#message").text(excuse);
}

$(document).ready(function(){
	$("#button").click(excuseGen);
	excuseGen();
});
