# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# plugins:

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

include:
  - _pages
  - _redirects

# Site settings
title: Ryan Arnaudin
myname: Ryan Arnaudin
email: arnaudin@ryanarnaudin.com
long-title: Ryan Arnaudin - Designer, Product Manager, Engineer
description: > # this means to ignore newlines until "baseurl:"
  "Ryan Arnaudin is a software builder in Austin, Texas."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ryanarnaudin.com" # the base hostname & protocol for your site
timezone: America/Chicago
year: 2022
start-year: 2008
sitemap: true

# Social
social-username:
  twitter: "@arnaudin"
  linkedin: "arnaudin"
  github: "arnaudin"
  medium: "@arnaudin"
  pinterest: "rarnaudin"
  instagram: "arnaudin"
  flickr: "arnaudin"
  spotify: "arnaudin"
  codepen: "arnaudin"
  strava: "2363619"
amazon_associate_id: ryanarna-20

# Content
image_serve_path: "/images" # <img src="{{ site.image_serve_path }}/projects/img.jpg">

# Build settings
markdown: kramdown

kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Sass output
sass:
  style: compressed # :nested :compact :expanded :compressed

compress_html: # http://jch.penibelst.de/
  enabled: true # compress html
  clippings: all # clip safe tags
  comments: []
  endings: []
  #ignore:
    #envs: [local]
  blanklines: false # boolean - strip blank lines and breaks
  profile: false
  startings: []


# Structure
navigation:
  - title: Work
    url: /
  - title: Blog
    url: /blog
  - title: About
    url: /about
  - title: Contact
    url: /contact

permalink: pretty

# Configure site collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  blog:
    output: true
    permalink: /blog/:path/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "blog"