#!/bin/bash
# Generates WebP versions of site images and records image dimensions for
# Jekyll templates. Run from the repo root after adding or changing images:
#
#     ./tools/optimize-images.sh
#
# Requires: cwebp (brew install webp), sips (built into macOS)
#
# Outputs:
#   - a .webp file next to every .png/.jpg/.jpeg under images/ (skips favicons)
#   - a .900w.webp variant for images wider than 1400px (mobile srcset)
#   - _data/image_dims.yml mapping /path (relative to images/) -> w/h/webp/w900
set -euo pipefail
cd "$(dirname "$0")/.."

QUALITY=85
DIMS_FILE="_data/image_dims.yml"

mkdir -p _data
echo "# Generated by tools/optimize-images.sh — do not edit by hand." > "$DIMS_FILE"

find images -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.gif" \) \
  -not -path "images/favicons/*" -not -name ".*" | sort | while read -r f; do

  w=$(sips -g pixelWidth "$f" 2>/dev/null | awk '/pixelWidth/{print $2}')
  h=$(sips -g pixelHeight "$f" 2>/dev/null | awk '/pixelHeight/{print $2}')
  [ -z "$w" ] && continue

  key="/${f#images/}"
  webp="false"
  w900="false"

  case "$f" in
    *.gif|*.GIF) ;; # dimensions only; no webp for gifs
    *)
      base="${f%.*}"
      if [ ! -f "$base.webp" ] || [ "$f" -nt "$base.webp" ]; then
        cwebp -quiet -q $QUALITY -sharp_yuv -metadata none "$f" -o "$base.webp"
      fi
      webp="true"
      if [ "$w" -gt 1400 ]; then
        if [ ! -f "$base.900w.webp" ] || [ "$f" -nt "$base.900w.webp" ]; then
          cwebp -quiet -q $QUALITY -sharp_yuv -metadata none -resize 900 0 "$f" -o "$base.900w.webp"
        fi
        w900="true"
      fi
      ;;
  esac

  {
    echo "\"$key\":"
    echo "  w: $w"
    echo "  h: $h"
    echo "  webp: $webp"
    echo "  w900: $w900"
  } >> "$DIMS_FILE"
done

echo "Done. $(grep -c '^"' "$DIMS_FILE") images indexed in $DIMS_FILE"
